export const state = Object.seal({
  session: null,
  appInfo: null,
  settings: null,
  playerStatus: null,
  dashboard: null,
  results: [],
  selectedAnime: null,
  episodes: [],
  playback: null,
  lastIssue: null,
  parentalUnlockedUntil: 0,
  pendingParentalAction: null,
  activeInstallationJob: null,
  installationProvider: null,
  currentListTab: 'favorites',
  users: [],
  update: null,
  updateBannerDismissed: false,
  telemetryPage: 1,
  telemetryPages: 1,
  telemetryFacetsLoaded: false,
  playerStatusHydration: null
});
